comment:
    layout: header, changes, diff, sunburst
coverage:
    status:
        patch:
            default:
                target: auto
        project:
            default:
                target: auto
